### ISSUE TITLE
Check Contentful embedly link

### ISSUE THREAD

**Issue by atreni** [JustFixNYC/eviction-free-nyc#23]
Doesn't always successfully load the map. Happens every 5th time or so:
![Screen Shot 2018-03-12 at 5.27.57 PM.png](https://images.zenhubusercontent.com/56720ac3638e718c995f75d9/57c69afa-cf91-4510-ba1b-2e592592e975)

**Comment by sraby** [comment]
We have not been able to recreate this issue, so closing for now!
