### ISSUE TITLE
IE11 logo svg not rendering 

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/eviction-free-nyc#39]
![image.png](https://images.zenhubusercontent.com/56438d5b638e718c995e7571/778cb100-a19f-49f4-aa31-fc5d846d3e54)

**Comment by sraby** [comment]
After checking this, the logo is rendering but with an incorrect aspect ratio. Since IE users represent less than 0.5% of our last month's user base, we will be closing this issue for now.
