### ISSUE TITLE
Issue with boro parsing for the Bronx

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/eviction-free-nyc#48]
I think google autocomplete used to just have "Bronx" as the boro field vs. "The Bronx". If you search for a Bronx address you now get a 404 upon submitting the screener:

![image](https://user-images.githubusercontent.com/627751/57645338-0c13b480-758c-11e9-8d37-5da1f9799621.png)

This was from searching for "1888 Grand Concourse, Bronx"

**Comment by sraby** [comment]
addressed in #49
