### ISSUE TITLE
Updates for administrative hearings

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/eviction-free-nyc#51]
NYCHA admin hearings have changed – now, if you are 62 or older, you have guaranteed access to counsel (regardless of zipcode)! 

To reflect those changes, we're going to make some additions to the `/admin-hearings` page:
1. Add an additional "To Do" step before "Go to Housing Court" in Contentful
2. Modify the admin hearings page title with new content: 

```
"If the head of household in your apartment is 62 years or older, and you have an administrative hearing at NYCHA, you have the right to an attorney. Otherwise, you still have options to get assistance."
```

This will entail overwriting the section in `<CourtPage />` that displays the qualified / not qualified title:

https://github.com/JustFixNYC/eviction-free-nyc/blob/master/src/containers/CourtPage.js#L35

**Comment by sraby** [comment]
This was fixed as part of PR #53
