### ISSUE TITLE
EFNYC Textbot: Create endpoints for determining eligibility and getting results title/URL

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/eviction-free-nyc#55]
For the EFNYC textbot, we want to ask the user similar questions as found on the site and then provide them a link to the appropriate results page and/or customized content (i.e. "You're eligible!"). In order to do this, we'll need to create a [Netlify Lambda Function](https://www.netlify.com/docs/functions/) to create an external way to call the functions found in `src/utils/logic.js`. These functions are:

`isLocationEligible()`: Given a zipcode, tells you if that zipcode is in RTC or not
`isNychaEligible()`: Given multiple zipcodes (because a NYCHA dev can have multiple zips, apparently), tells you if that zipcode is in RTC or not. We might not need this one for the textbot.
`determineResultPage()`: Given a `user` object which contains the following key/value pairs:

- `zip`: user's zip
- `boro`: user's borough
- `caseType`: user's case type, which can be "nonpay", "holdover", "general", or "other" (see `src/components/steps/StepCasetype.js`)
- `areaEligible`: boolean result of calling `isLocationEligible()`
- `incomeEligible` boolean based on user input
- `nycha` boolean based on user input

this function will determine the proper results page to then send to the user. In the current codebase, it uses gatsby's `navigateTo` function to trigger a redirect; this is something to factor out so this function just creates the url and `navigateTo` is handled somewhere else (most likely at [/src/containers/ScreenerPage.js#L123](https://github.com/JustFixNYC/eviction-free-nyc/blob/master/src/containers/ScreenerPage.js#L123)). There is also a `intl` parameter which we should be able to send from TextIt as well (essentially specifying the language the user is in)

Once this endpoint is created, it should be easy to create a webhook in TextIt to query for this results info/url! Let me know if you have questions!

**Comment by romeboards** [comment]
@sraby We had talked recently about Netlify Lambda functions – this is where I think they'd be super useful for EFNYC

**Comment by abromanos** [comment]
pushed to prod! :~) thanks for an amazing summer!
